### PR TITLE
fix Layout Format %q output

### PR DESCRIPTION
**Pull request by compatc**

### CODE REVIEW

**Comment by novalagung** [comment]
hi @compatc, thx for the pr.

can you do me a favor, please put your name to the CONTRIBUTORS.md. then I will merge the PR.

**Comment by compatc** [comment]
update di contributeors.md dan pull request lagi ya?

**Comment by novalagung** [comment]
@compatc cukup komit lalu push aja ke branch master. nnti otomatis masuk ke pr ini

**Comment by compatc** [comment]
@novalagung done

**Pull request merged**
