### PR TITLE
improve texts

### PR DESCRIPTION
**Pull request by novalagung**

### CODE REVIEW

**Comment by bokunodev** [comment]
why you remove the square brackets ?

**Comment by novalagung** [comment]
@bokunodev see this https://github.com/novalagung/dasarpemrogramangolang/issues/16

some people think the remarked info next to the statement is the "literal" representation of the output. and that is not what I'm trying to tell in the content.

So rather than change it to this:

```
fmt.Println(strings.Split("football", ""))   	// [f o o t b a l l]
```

which is clear for experienced people but quite confusing for newbie. I chose to make it:

```
fmt.Println(strings.Split("football", ""))   	// output: "f", "o", "o", "t", "b" "a", "l", "l"
```

**Comment by novalagung** [comment]
@bokunodev have better suggestions for that?

**Comment by novalagung** [comment]
nevermind. I think I'm going to put it back, but keeping the "output" text

**Pull request merged**
