### PR TITLE
Update 39-timer.md (fixing typo)

### PR DESCRIPTION
**Pull request by cacing69**
fixing typo ditentikan  -> ditentukan

### CODE REVIEW

**Comment by novalagung** [comment]
nice catch! can you please add your name into the `CONTRIBUTORS.md` file in ascending order? I will merge it afterward

**Comment by cacing69** [comment]
> nice catch! can you please add your name into the `CONTRIBUTORS.md` file in ascending order? I will merge it afterward

ahh with pleasure 😄

**Comment by novalagung** [comment]
LGTM

**Comment by novalagung** [comment]
Thank you for the contribution

**Pull request merged**
